[project]
name = "minapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arel>=0.4.0",
    "fastapi[standard]>=0.129.0",
    "jinja2>=3.1.6",
]
